### ISSUE TITLE
Type of a local variable inferred from a PHPUnit class

### ISSUE THREAD

**Issue by kielabokkie** [JetBrains/pest-intellij#270] opened 2022-04-14 02:42 UTC
We are in the process of adding Pest to an existing Symfony project. I've created a separate folder for Pest `tests/Pest/Unit` while the existing PHPUnit tests live in `tests/Unit`, `tests/Functional` etc. When I try to instantiate a local variable in the `beforeEach()` function it is somehow picking up the type from a PHPUnit test.

For example, a PHPUnit test in the folder `tests/Functional/FooTest.php` initialises a `$user` property:
```php
class CrudTest extends BaseWebTestCase
{
    private User $user;
}
```

When I try to do the following in my Pest test `tests/Unit/BarTest.php`
```php
beforeEach(function (): void {
    $this->user = 'test';
});
```

PhpStorm will complain about incompatible types because it's expecting a `User` object instead of a string. How do I prevent PhpStorm from inferring types from other totally unrelated PHPUnit tests?

**Comment by olivernybroe** [comment] 2022-04-14 06:58
Hmm this sounds pretty weird. 
I tried a couple of times and haven't been able to reproduce yet. Would you be able to supply with a simple reproducible example?

**Comment by kielabokkie** [comment] 2022-04-16 07:22
@olivernybroe I've created a basic Laravel project to replicate the issue: https://github.com/kielabokkie/pest-issue.

As you can see in the screenshot below I have a separate `tests/Pest` folder and the default `test/Unit` folder that comes with Laravel. Somehow the public property `$user` of my `ExampleTest.php` class is picked up in the `beforeEach` function of my `PestExampleTest.php` class.

<img width="1728" alt="Screen Shot 2022-04-16 at 7 13 26 PM" src="https://user-images.githubusercontent.com/1221750/163665753-3590f79c-7a50-421a-951f-3333f983250f.png">

**Comment by olivernybroe** [comment] 2022-04-16 07:40
Awesome, thanks for providing an example, so we can reproduce it 🤩

**Comment by isfedorov** [comment] 2023-11-16 19:29
@kielabokkie Thank you for the provided example! The real issue is that type of `$this` is inferred wrong by PhpStorm in context of Pest test. Due to Pest plugin as of now is maintained by PhpStorm team, we are going to gradually move all the reports from GitHub to YouTrack so that we have the single source of tickets. I've created a dedicated ticket for this particular problem in YouTrack [WI-75119](https://youtrack.jetbrains.com/issue/WI-75119) so you can track the state of the issue and vote there. Also I've attached your example project to the ticket, thank you for it one more time. So for now I'm going to close this ticket and if you have any comments or other problems with Pest plugin, please report them to [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WI)

**Closed by isfedorov** 2023-11-16 19:29 UTC
Labels: bug
