### ISSUE TITLE
PhpStorm Autocomplete not working in closures

### ISSUE THREAD

**Issue by Sans84** [JetBrains/pest-intellij#500] opened 2023-09-25 20:35 UTC
**Describe the bug**
in continuation of the issue #331 

**To Reproduce**
1. Create a new Laravel project
2. Added Pest according to the installation guide
3. Installed the Pest plugin for PHPStorm
4. Created a test

The result is that the autocomplete for closures does not work

5. Disabled all installed plugins except Pest.

It does not work.

6. Entered the changes as written in the past issue: `uses(TestCase::class)->in('./');`

It does not work

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - IntelliJ Version: PHPStorm 2023.2 last build
 - Plugin Version 1.11.0

**Comment by olivernybroe** [comment] 2023-09-26 07:07
@Sans84 could you elaborate on when it doesn't work? 

What are you writing where you expect autocompletion to trigger and what are you expecting to show? 
For example is it related to the expectation API, using `$this` etc.

**Comment by Sans84** [comment] 2023-09-26 14:20
> @Sans84 could you elaborate on when it doesn't work?
> 
> What are you writing where you expect autocompletion to trigger and what are you expecting to show? For example is it related to the expectation API, using `$this` etc.

For `$this->` or function it works
<img width="614" alt="image" src="https://github.com/pestphp/pest-intellij/assets/18501836/9a609781-aa20-442b-9f92-5ab338f94271">
<img width="413" alt="image" src="https://github.com/pestphp/pest-intellij/assets/18501836/2f9934fd-d9c8-476f-b5c5-5e05db49f152">

but does not work for the chain:
<img width="257" alt="image" src="https://github.com/pestphp/pest-intellij/assets/18501836/162043c3-b553-4237-9581-a8a9e6375c5c">

**Comment by isfedorov** [comment] 2023-11-16 18:54
@Sans84 I've tried to reproduce the problem with PhpStorm 2023.2.3 and Pest plugin 1.11.0 with [laravel.io](https://github.com/laravelio/laravel.io) project but no luck. Completion works just fine for me
<img width="868" alt="Screenshot 2023-11-16 at 7 46 16 PM" src="https://github.com/JetBrains/pest-intellij/assets/37301285/a74888b5-c219-4831-90b3-51e0282aa2cb">
Could you please invoke `File->Invalidate caches & restart`, in PhpStorm, what until indexing is complete and check if the issue will occur after that?

**Comment by olivernybroe** [comment] 2023-11-16 20:51
@isfedorov how does your `pest.php` config look like? 
The important part here is `uses(TestCase::class)->in('./');` in the `pest.php` file.

**Comment by isfedorov** [comment] 2023-11-16 22:07
@olivernybroe Originally laravel.io project didn't have such statement in config, I've added
```
use Tests\TestCase;

uses(TestCase::class)->in('./');
```
And still completion works fine.
After that I've tried to open [project](https://gitlab.com/jadonbrown/pest-test.git) from related ticket (it contains such `uses` statement as well), tried completion in that project and still everything works fine 
<img width="850" alt="Screenshot 2023-11-16 at 11 06 26 PM" src="https://github.com/JetBrains/pest-intellij/assets/37301285/056947f4-4945-49c2-9463-125972444b85">

**Comment by isfedorov** [comment] 2023-12-07 10:22
As far as there was no any answer and I can't reproduce the issue on my side, I tend to close this issue. If you still experience such a problem please create a ticket in [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WI) and we will investigate it further.

**Closed by isfedorov** 2023-12-07 10:22 UTC
Labels: bug
